import assert from 'node:assert/strict';
import { createServer } from 'vite';

const server = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'silent' });

try {
  const { createInitialState, MACHINE_IDS, UPGRADE_IDS } = await server.ssrLoadModule('/src/state.ts');
  const clips = await server.ssrLoadModule('/src/game/clips.ts');
  const combo = await server.ssrLoadModule('/src/game/combo.ts');
  const progression = await server.ssrLoadModule('/src/game/progression.ts');
  const milestones = await server.ssrLoadModule('/src/game/milestones.ts');
  const achievements = await server.ssrLoadModule('/src/game/achievements.ts');
  const bonusEvents = await server.ssrLoadModule('/src/game/bonusEvents.ts');
  const signalLab = await server.ssrLoadModule('/src/game/signalLab.ts');
  const directives = await server.ssrLoadModule('/src/game/directives.ts');
  const reboot = await server.ssrLoadModule('/src/game/reboot.ts');
  const survey = await server.ssrLoadModule('/src/game/survey.ts');
  const capacitor = await server.ssrLoadModule('/src/game/capacitor.ts');
  const overclock = await server.ssrLoadModule('/src/game/overclock.ts');
  const fold = await server.ssrLoadModule('/src/game/fold.ts');
  const gauge = await server.ssrLoadModule('/src/game/gauge.ts');
  const catalyst = await server.ssrLoadModule('/src/game/catalyst.ts');
  const dispatch = await server.ssrLoadModule('/src/game/dispatch.ts');
  const patch = await server.ssrLoadModule('/src/game/patch.ts');
  const wind = await server.ssrLoadModule('/src/game/wind.ts');
  const pulse = await server.ssrLoadModule('/src/game/pulse.ts');
  const scrap = await server.ssrLoadModule('/src/game/scrap.ts');

  const state = createInitialState(0);
  assert.equal(combo.comboMultiplier(1), 1);
  assert.equal(combo.comboMultiplier(2), 1.15);
  assert.equal(combo.comboMultiplier(12), 2.65);
  assert.equal(combo.comboMultiplier(99), 2.65);
  assert.equal(combo.nextCombo(0, 0, 1000), 1);
  assert.equal(combo.nextCombo(3, 1000, 1500), 4);
  assert.equal(combo.nextCombo(3, 1000, 2000), 1);
  assert.equal(combo.nextCombo(12, 1000, 1500), 12);
  assert.equal(combo.comboExpired(4, 1000, 1701), true);
  const comboClick = createInitialState(0);
  const comboResult = clips.produceByClick(comboClick, 12);
  assert.equal(comboResult.critical ? comboResult.amount / 5 : comboResult.amount, 2.65);
  assert.equal(clips.machinePrice(state, 'autoClipper'), 15);
  assert.equal(clips.machineBatchPrice(state, 'autoClipper', 2), 33);

  state.clips = 100;
  assert.deepEqual(clips.selectedPurchase(state, 'autoClipper', 'max'), { count: 4, price: 76 });
  assert.equal(clips.buyMachines(state, 'autoClipper', 'max'), 4);
  assert.equal(state.machines.autoClipper, 4);
  assert.equal(state.clips, 24);
  assert.ok(Math.abs(clips.productionPerSecond(state) - 0.408) < 1e-9);

  state.upgrades.push('qualityCutter', 'selfImprovement', 'recursiveMandate');
  assert.ok(Math.abs(clips.productionPerSecond(state) - 2.496) < 1e-9);

  assert.equal(milestones.milestoneStatus(9).multiplier, 1);
  assert.equal(milestones.milestoneStatus(10).multiplier, 2);
  assert.equal(milestones.milestoneStatus(25).multiplier, 4);
  assert.equal(milestones.milestoneStatus(50).multiplier, 8);
  assert.equal(milestones.milestoneStatus(100).multiplier, 16);
  assert.deepEqual(milestones.crossedMilestones(9, 26).map((item) => item.count), [10, 25]);

  state.machines.autoClipper = 10;
  assert.ok(Math.abs(clips.machineTotalProduction(state, 'autoClipper') - 12.72) < 1e-9);
  assert.equal(milestones.totalAchievedMilestones(state), 1);

  const achievementState = createInitialState(0);
  assert.equal(achievements.unlockedAchievements(achievementState).length, 0);
  assert.equal(achievements.achievementProductionMultiplier(achievementState), 1);
  achievementState.totalClips = 1_000_000_000;
  for (const id of MACHINE_IDS) achievementState.machines[id] = 10;
  achievementState.upgrades = [...UPGRADE_IDS];
  assert.equal(achievements.unlockedAchievements(achievementState).length, 14);
  assert.equal(achievements.achievementProductionMultiplier(achievementState), 1.28);
  assert.ok(achievements.unlockedAchievementIds(achievementState).includes('fullSpectrum'));

  assert.equal(bonusEvents.nextBonusDelay(() => 0, true), 20);
  assert.ok(bonusEvents.nextBonusDelay(() => 0.999, true) < 40);
  assert.equal(bonusEvents.nextBonusDelay(() => 0), 30);
  assert.ok(bonusEvents.nextBonusDelay(() => 0.999) < 75);
  assert.equal(bonusEvents.chooseBonusOutcome(() => 0), 'productionCache');
  assert.equal(bonusEvents.chooseBonusOutcome(() => 0.9), 'inventoryEcho');
  assert.equal(bonusEvents.nextPrecisionDelay(() => 0, true), 8);
  assert.ok(bonusEvents.nextPrecisionDelay(() => 0.999, true) < 16);
  assert.equal(bonusEvents.nextPrecisionDelay(() => 0), 12);
  assert.ok(bonusEvents.nextPrecisionDelay(() => 0.999) < 28);
  assert.equal(bonusEvents.precisionClickTarget(() => 0), 3);
  assert.equal(bonusEvents.precisionClickTarget(() => 0.999), 7);
  assert.equal(bonusEvents.precisionPosition(() => 0), 0);
  assert.equal(bonusEvents.precisionPosition(() => 0.999), 5);
  const bonusState = createInitialState(0);
  assert.equal(bonusEvents.calculateBonusReward(bonusState, 'productionCache'), 100);
  bonusState.clips = 10_000;
  const echoReward = bonusEvents.applyBonusReward(bonusState, 'inventoryEcho');
  assert.equal(echoReward.amount, 1_000);
  assert.equal(bonusState.clips, 11_000);
  assert.equal(bonusState.totalClips, 1_000);
  assert.equal(bonusState.bonusEventsCollected, 1);
  const precisionReward = bonusEvents.applyPrecisionReward(bonusState, 3);
  assert.equal(precisionReward, 250);
  assert.equal(bonusState.precisionTargetsCompleted, 1);

  const signalState = createInitialState(0);
  signalState.clips = 100_000;
  assert.equal(signalLab.signalBuffCost('productionSurge', 0), 1_000);
  assert.equal(signalLab.signalBuffCost('precisionAssist', 10), 6_000);
  assert.equal(signalLab.activateSignalBuff(signalState, 'productionSurge', 0, 1_000), true);
  assert.equal(signalState.clips, 99_000);
  assert.equal(signalLab.isSignalBuffActive(signalState, 'productionSurge', 1_001), true);
  assert.equal(signalLab.signalEquipmentMultiplier(signalState, 1_001), 2);
  assert.equal(signalLab.signalClickMultiplier(signalState, 1_001), 1);
  assert.equal(signalLab.activateSignalBuff(signalState, 'productionSurge', 0, 1_001), false);
  signalState.signalBuffExpiresAt.precisionAssist = 999_999;
  signalState.signalBuffExpiresAt.signalBeacon = 999_999;
  assert.equal(signalLab.signalEquipmentMultiplier(signalState, 2_000), 3);
  assert.equal(signalLab.signalClickMultiplier(signalState, 2_000), 3);
  assert.equal(signalLab.signalIntervalMultiplier(signalState, 2_000), 0.6);
  assert.equal(signalLab.anomalyRewardMultiplier(signalState, 2_000), 3);
  assert.equal(signalLab.precisionRewardMultiplier(signalState, 2_000), 3);
  assert.equal(signalLab.precisionDuration(signalState, 4, 2_000), 5);

  const directiveState = createInitialState(0);
  directiveState.clips = 100;
  assert.equal(directives.directiveTarget(directiveState, 'manualCalibration'), 25);
  assert.equal(directives.directiveTarget(directiveState, 'procurementOrder'), 10);
  assert.equal(directives.directiveTarget(directiveState, 'signalCapture'), 3);
  assert.equal(directives.directiveReward(directiveState, 'manualCalibration'), 250);
  directives.advanceDirective(directiveState, 'manualCalibration', 27);
  assert.equal(directives.canClaimDirective(directiveState, 'manualCalibration'), true);
  assert.equal(directives.claimDirective(directiveState, 'manualCalibration'), 250);
  assert.equal(directiveState.directiveProgress.manualCalibration, 2);
  assert.equal(directiveState.directiveCompletions.manualCalibration, 1);
  assert.equal(directives.directiveTarget(directiveState, 'manualCalibration'), 30);
  assert.equal(directives.directiveReward(directiveState, 'manualCalibration'), 313);

  const rebootState = createInitialState(0);
  rebootState.totalClips = 4_000_000_000;
  rebootState.clips = 123;
  rebootState.machines.autoClipper = 10;
  rebootState.settings.theme = 'dark';
  rebootState.purchaseMode = 'max';
  assert.equal(reboot.rebootCoreGain(rebootState), 2);
  assert.equal(reboot.canReboot(rebootState), true);
  const rebooted = reboot.createRebootedState(rebootState, 10);
  assert.equal(rebooted.optimizationCores, 2);
  assert.equal(rebooted.rebootCount, 1);
  assert.equal(rebooted.totalClips, 0);
  assert.equal(rebooted.machines.autoClipper, 0);
  assert.equal(rebooted.settings.theme, 'dark');
  assert.equal(rebooted.purchaseMode, 'max');
  assert.equal(reboot.rebootMultiplier(rebooted), 1.5);
  assert.equal(clips.clickProduction(rebooted), 1.5);

  assert.equal(survey.surveyCost('near', 0), 400);
  assert.equal(survey.surveyCost('near', 100), 2_000);
  assert.equal(survey.surveyReward('far', 0), 20_000);
  const surveyState = createInitialState(0);
  surveyState.clips = 1_000;
  surveyState.totalClips = 10_000;
  assert.equal(survey.isSurveyUnlocked(surveyState), true);
  assert.equal(survey.launchSurvey(surveyState, 'near', 1_000), true);
  assert.equal(survey.surveyStatus(surveyState, 'near', 1_000), 'outbound');
  assert.equal(survey.collectSurvey(surveyState, 'near', 1_000), 0);
  assert.equal(survey.surveyStatus(surveyState, 'near', 16_000), 'ready');
  const surveyReward = survey.collectSurvey(surveyState, 'near', 16_000);
  assert.equal(surveyReward, 600);
  assert.equal(surveyState.surveysRecovered, 1);
  assert.equal(survey.surveyStatus(surveyState, 'near', 16_000), 'idle');

  const capState = createInitialState(0);
  capState.totalClips = 100;
  capState.machines.autoClipper = 10;
  assert.equal(capacitor.isCapacitorUnlocked(capState), true);
  assert.equal(capacitor.capacitorCapacity(createInitialState(0)), 50);
  const charged = capacitor.chargeCapacitor(capState, 10);
  assert.ok(charged > 0);
  const claimed = capacitor.claimCapacitor(capState);
  assert.equal(claimed, charged);
  assert.equal(capState.capacitorStored, 0);
  assert.equal(capState.capacitorClaims, 1);
  assert.equal(capacitor.claimCapacitor(capState), 0);

  assert.equal(overclock.overclockCost(0), 250);
  assert.equal(overclock.overclockCost(20), 500);
  const ocState = createInitialState(0);
  ocState.totalClips = 250;
  ocState.clips = 250;
  ocState.machines.autoClipper = 1;
  assert.equal(overclock.isOverclockUnlocked(ocState), true);
  const baseRate = clips.machineUnitProduction(ocState, 'autoClipper');
  const ocNow = Date.now();
  assert.equal(overclock.canStartOverclock(ocState, 'autoClipper', 0, ocNow), true);
  assert.equal(overclock.startOverclock(ocState, 'autoClipper', 0, ocNow), true);
  assert.equal(ocState.overclockMachine, 'autoClipper');
  assert.equal(ocState.overclockExpiresAt, ocNow + 20_000);
  assert.equal(ocState.overclockCount, 1);
  assert.equal(ocState.clips, 0);
  assert.equal(overclock.overclockMultiplier(ocState, 'autoClipper', ocNow), 3);
  assert.equal(overclock.overclockMultiplier(ocState, 'wireMachine', ocNow), 1);
  assert.equal(clips.machineUnitProduction(ocState, 'autoClipper'), baseRate * 3);
  assert.equal(overclock.canStartOverclock(ocState, 'wireMachine', 0, ocNow), false);
  assert.equal(overclock.overclockMultiplier(ocState, 'autoClipper', ocNow + 20_000), 1);
  assert.equal(clips.clickProduction(ocState), 1);

  assert.equal(fold.foldCost(0), 50);
  assert.equal(fold.foldCost(10), 80);
  assert.equal(fold.foldReward(0), 80);
  assert.equal(fold.foldReward(10), 200);
  const foldState = createInitialState(0);
  foldState.totalClips = 200;
  foldState.clips = 50;
  assert.equal(fold.isFoldUnlocked(foldState), true);
  const foldNow = Date.now();
  assert.equal(fold.canStartFold(foldState, 0, foldNow), true);
  const folded = fold.startFold(foldState, 0, foldNow);
  assert.equal(folded, 80);
  assert.equal(foldState.clips, 80);
  assert.equal(foldState.totalClips, 280);
  assert.equal(foldState.foldCount, 1);
  assert.equal(foldState.foldExpiresAt, foldNow + 15_000);
  assert.equal(fold.canStartFold(foldState, 0, foldNow), false);
  assert.equal(fold.startFold(foldState, 0, foldNow), 0);
  assert.equal(fold.canStartFold(foldState, 0, foldNow + 15_000), true);

  assert.equal(gauge.gaugeReward(0), 20);
  assert.equal(gauge.gaugeReward(10), 60);
  assert.equal(gauge.nextGaugeTarget(0, () => 0), 1);
  assert.equal(gauge.nextGaugeTarget(0, () => 0.9), 2);
  const gaugeState = createInitialState(0);
  gaugeState.totalClips = 150;
  assert.equal(gauge.isGaugeUnlocked(gaugeState), true);
  const gaugeNow = Date.now();
  assert.equal(gauge.pickGauge(gaugeState, 1, 0, gaugeNow), 0);
  assert.equal(gaugeState.gaugeHits, 0);
  assert.equal(gauge.pickGauge(gaugeState, 0, 0, gaugeNow), 0);
  const gauged = gauge.pickGauge(gaugeState, 0, 0, gaugeNow + 2_000, () => 0);
  assert.equal(gauged, 20);
  assert.equal(gaugeState.clips, 20);
  assert.equal(gaugeState.totalClips, 170);
  assert.equal(gaugeState.gaugeHits, 1);
  assert.equal(gaugeState.gaugeTarget, 1);
  assert.equal(gauge.pickGauge(gaugeState, 1, 0, gaugeNow + 2_000), 0);
  assert.equal(gauge.pickGauge(gaugeState, 1, 0, gaugeNow + 2_000 + 8_000, () => 0.9), 20);
  assert.equal(gaugeState.gaugeTarget, 2);

  assert.equal(catalyst.catalystDrainPerSecond(0), 0.5);
  assert.equal(catalyst.catalystDrainPerSecond(10), 2);
  const catState = createInitialState(0);
  catState.totalClips = 180;
  catState.clips = 100;
  catState.machines.autoClipper = 10;
  assert.equal(catalyst.isCatalystUnlocked(catState), true);
  const unboosted = clips.productionPerSecond(catState);
  assert.ok(unboosted > 0);
  assert.equal(catalyst.catalystMultiplier(catState), 1);
  assert.equal(catalyst.toggleCatalyst(catState, unboosted), true);
  assert.equal(catState.catalystActive, true);
  assert.equal(catalyst.catalystMultiplier(catState), 1.4);
  assert.ok(Math.abs(clips.productionPerSecond(catState) - unboosted * 1.4) < 1e-9);
  assert.equal(clips.clickProduction(catState), 1);
  const drained = catalyst.tickCatalyst(catState, 1, unboosted);
  assert.equal(drained, catalyst.catalystDrainPerSecond(unboosted));
  assert.ok(Math.abs(catState.clips - (100 - drained)) < 1e-9);
  assert.equal(catState.catalystSeconds, 1);
  assert.equal(catalyst.toggleCatalyst(catState, unboosted), true);
  assert.equal(catState.catalystActive, false);
  catState.clips = 0.1;
  catState.catalystActive = true;
  assert.equal(catalyst.tickCatalyst(catState, 1, unboosted), 0);
  assert.equal(catState.catalystActive, false);

  assert.equal(dispatch.dispatchCapacity(0), 40);
  assert.equal(dispatch.dispatchCapacity(10), 150);
  const shipState = createInitialState(0);
  shipState.totalClips = 160;
  assert.equal(dispatch.isDispatchUnlocked(shipState), true);
  const shippedCharge = dispatch.chargeDispatch(shipState, 10, 10, 1_000);
  assert.equal(shippedCharge, 20);
  assert.equal(shipState.dispatchStored, 20);
  assert.equal(dispatch.dispatchStatus(shipState, 1_000), 'filling');
  assert.equal(dispatch.startDispatch(shipState, 1_000), true);
  assert.equal(dispatch.dispatchStatus(shipState, 1_000), 'transit');
  assert.equal(dispatch.chargeDispatch(shipState, 10, 10, 1_000), 0);
  assert.equal(dispatch.collectDispatch(shipState, 1_000), 0);
  assert.equal(dispatch.dispatchStatus(shipState, 11_000), 'ready');
  const shipped = dispatch.collectDispatch(shipState, 11_000);
  assert.equal(shipped, 32);
  assert.equal(shipState.dispatchStored, 0);
  assert.equal(shipState.dispatchClaims, 1);
  assert.equal(shipState.clips, 32);
  assert.equal(dispatch.dispatchStatus(shipState, 11_000), 'filling');

  assert.equal(patch.patchCost(createInitialState(0), 0), 25);
  assert.equal(patch.patchCost(createInitialState(0), 10), 40);
  const priced = createInitialState(0);
  priced.patchCount = 1;
  assert.equal(patch.patchCost(priced, 10), 52);
  assert.equal(patch.patchMultiplier(createInitialState(0)), 1);
  priced.patchCount = 5;
  assert.equal(patch.patchMultiplier(priced), 1.2);
  priced.patchCount = 20;
  assert.equal(patch.patchMultiplier(priced), 1.8);
  assert.equal(patch.isPatchMaxed(priced), true);
  const revState = createInitialState(0);
  revState.totalClips = 120;
  revState.clips = 10_000;
  revState.machines.autoClipper = 10;
  assert.equal(patch.isPatchUnlocked(revState), true);
  const patchBase = clips.productionPerSecond(revState);
  assert.equal(patch.buyPatch(revState, 0), true);
  assert.equal(revState.patchCount, 1);
  assert.ok(Math.abs(clips.productionPerSecond(revState) - patchBase * 1.04) < 1e-9);
  assert.equal(clips.clickProduction(revState), 1);
  revState.patchCount = 20;
  assert.equal(patch.buyPatch(revState, 0), false);

  assert.equal(wind.windReward(0.2, 10), 0);
  assert.equal(wind.windReward(0.4, 10), 20);
  assert.equal(wind.windReward(3, 10), 150);
  assert.equal(wind.windReward(9, 10), 150);
  const windState = createInitialState(0);
  windState.totalClips = 140;
  assert.equal(wind.isWindUnlocked(windState), true);
  const windNow = Date.now();
  assert.equal(wind.releaseWind(windState, 0.2, 10, windNow), 0);
  assert.equal(windState.windCount, 0);
  const wound = wind.releaseWind(windState, 1, 10, windNow);
  assert.equal(wound, 50);
  assert.equal(windState.windCount, 1);
  assert.equal(windState.clips, 50);
  assert.equal(wind.releaseWind(windState, 3, 10, windNow), 0);
  assert.equal(wind.releaseWind(windState, 3, 10, windNow + 8_000), 150);

  assert.equal(pulse.pulseReward(0), 20);
  assert.equal(pulse.pulseReward(10), 80);
  const pulseState = createInitialState(0);
  pulseState.totalClips = 130;
  assert.equal(pulse.isPulseUnlocked(pulseState), true);
  const pulseNow = Date.now();
  assert.equal(pulse.isPulseReady(pulseState, pulseNow), true);
  const pulsed = pulse.claimPulse(pulseState, 10, pulseNow);
  assert.equal(pulsed, 80);
  assert.equal(pulseState.pulseCount, 1);
  assert.equal(pulseState.clips, 80);
  assert.equal(pulse.claimPulse(pulseState, 10, pulseNow), 0);
  assert.equal(pulse.claimPulse(pulseState, 10, pulseNow + 20_000), 80);

  assert.equal(scrap.scrapCapacity(0), 30);
  assert.equal(scrap.scrapCapacity(10), 200);
  const scrapState = createInitialState(0);
  scrapState.totalClips = 110;
  assert.equal(scrap.isScrapUnlocked(scrapState), true);
  assert.equal(scrap.chargeScrap(scrapState, 100, 10), 8);
  assert.equal(scrapState.scrapStored, 8);
  const scrapClaimed = scrap.claimScrap(scrapState);
  assert.equal(scrapClaimed, 8);
  assert.equal(scrapState.scrapStored, 0);
  assert.equal(scrapState.scrapClaims, 1);
  assert.equal(scrap.claimScrap(scrapState), 0);
  scrapState.scrapStored = 199;
  assert.equal(scrap.chargeScrap(scrapState, 100, 10), 1);
  const buyScrap = createInitialState(0);
  buyScrap.totalClips = 110;
  buyScrap.clips = 15;
  assert.equal(clips.buyMachines(buyScrap, 'autoClipper', 1), 1);
  assert.ok(Math.abs(buyScrap.scrapStored - 1.2) < 1e-9);

  state.totalClips = 50_000;
  const unlocked = clips.updateUnlocks(state);
  assert.ok(unlocked.includes('nanoForge'));
  assert.equal(progression.currentPhase(state).id, 'nano');
  assert.equal(progression.nextProductionGoal(state).name, 'スウォーム組立群');

  state.totalClips = 50_000_000;
  clips.updateUnlocks(state);
  assert.equal(state.unlockedMachines.length, 8);
  assert.equal(progression.currentPhase(state).id, 'matter');

  let storedSave = JSON.stringify({ ...state, purchaseMode: 'max', bonusEventsCollected: 7, precisionTargetsCompleted: 4, signalBuffExpiresAt: { productionSurge: 5_000, precisionAssist: 0, signalBeacon: 0 }, directiveProgress: { manualCalibration: 9, procurementOrder: 2, signalCapture: 1 }, directiveCompletions: { manualCalibration: 3, procurementOrder: 1, signalCapture: 2 }, lastSavedAt: 1_000 });
  globalThis.localStorage = {
    getItem: () => storedSave,
    setItem: (_key, value) => { storedSave = value; },
    removeItem: () => { storedSave = null; },
  };
  const save = await server.ssrLoadModule('/src/save.ts');
  const loaded = save.loadGame(1_000);
  assert.equal(loaded.state.purchaseMode, 'max');
  assert.equal(loaded.state.machines.matterCompiler, state.machines.matterCompiler);
  assert.equal(loaded.state.bonusEventsCollected, 7);
  assert.equal(loaded.state.precisionTargetsCompleted, 4);
  assert.equal(loaded.state.signalBuffExpiresAt.productionSurge, 5_000);
  assert.equal(loaded.state.directiveProgress.manualCalibration, 9);
  assert.equal(loaded.state.directiveCompletions.signalCapture, 2);
  assert.equal(loaded.state.optimizationCores, 0);

  state.totalClips = 500_000_000_000;
  clips.updateUnlocks(state);
  assert.equal(state.unlockedMachines.length, 12);
  assert.equal(progression.currentPhase(state).id, 'causal');

  assert.equal(clips.criticalChance(state), 0.05);
  assert.equal(clips.criticalMultiplier(state), 5);
  state.upgrades.push('overloadProtocol', 'resonanceAmplification');
  assert.equal(clips.criticalChance(state), 0.1);
  assert.equal(clips.criticalMultiplier(state), 8);

  assert.equal(clips.machinePrice(createInitialState(0), 'planetaryAssembler'), 1_800_000_000);
  assert.equal(clips.machinePrice(createInitialState(0), 'causalOptimizer'), 2_100_000_000_000);

  const autoState = createInitialState(0);
  assert.equal(clips.isAutoBuyUnlocked(autoState), false);
  assert.deepEqual(clips.autoBuyTick(autoState), []);
  autoState.clips = 1_100;
  autoState.autoBuyEnabled.autoClipper = true;
  assert.deepEqual(clips.autoBuyTick(autoState), []);
  autoState.upgrades.push('autoBuyCore');
  assert.equal(clips.isAutoBuyUnlocked(autoState), true);
  const boughtIds = clips.autoBuyTick(autoState);
  assert.deepEqual(boughtIds, ['autoClipper']);
  assert.equal(autoState.machines.autoClipper, 1);
  assert.equal(autoState.clips, 1_085);
  autoState.autoBuyEnabled.autoClipper = false;
  autoState.autoBuyEnabled.wireMachine = true;
  assert.deepEqual(clips.autoBuyTick(autoState), []);

  let autoSave = JSON.stringify({ ...autoState, autoBuyEnabled: { autoClipper: true } });
  globalThis.localStorage = {
    getItem: () => autoSave,
    setItem: (_key, value) => { autoSave = value; },
    removeItem: () => { autoSave = null; },
  };
  const autoLoaded = save.loadGame(0);
  assert.equal(autoLoaded.state.autoBuyEnabled.autoClipper, true);
  assert.equal(autoLoaded.state.autoBuyEnabled.wireMachine, false);

  const observation = await server.ssrLoadModule('/src/game/observation.ts');
  const observeState = createInitialState(0);
  assert.equal(observation.phaseRewardAmount(observeState), 100);
  observeState.machines.autoClipper = 10;
  const expectedReward = Math.max(100, clips.productionPerSecond(observeState) * 90);
  assert.equal(observation.phaseRewardAmount(observeState), expectedReward);
  observeState.totalClips = 50;
  observeState.clips = 50;
  const firstGrant = observation.grantDuePhaseRewards(observeState);
  assert.equal(firstGrant.length, 1);
  assert.equal(firstGrant[0].phase.id, 'mechanized');
  assert.equal(observeState.phaseRewardsGranted.includes('mechanized'), true);
  const clipsAfterGrant = observeState.clips;
  const secondGrant = observation.grantDuePhaseRewards(observeState);
  assert.equal(secondGrant.length, 0);
  assert.equal(observeState.clips, clipsAfterGrant);

  observeState.totalClips = 5_000_000_000;
  const multiGrant = observation.grantDuePhaseRewards(observeState);
  assert.ok(multiGrant.length >= 5);
  assert.equal(multiGrant.at(-1).phase.id, 'stellar');

  const legacySave = JSON.stringify({
    version: 1,
    clips: 80_000,
    totalClips: 80_000,
    machines: { autoClipper: 1 },
    upgrades: [],
    unlockedMachines: ['autoClipper'],
    playTimeSeconds: 10,
    startedAt: 0,
    lastSavedAt: 0,
    settings: { theme: 'dark', compactNumbers: true },
    purchaseMode: 1,
    bonusEventsCollected: 0,
    autoBuyEnabled: {},
  });
  globalThis.localStorage = {
    getItem: () => legacySave,
    setItem: () => {},
    removeItem: () => {},
  };
  const legacyLoaded = save.loadGame(0);
  assert.ok(legacyLoaded.state.phaseRewardsGranted.includes('nano'));
  assert.equal(legacyLoaded.state.clips, 80_000);
  assert.equal(legacyLoaded.state.interiorHarvests, 0);
  assert.equal(legacyLoaded.state.traceAiSuccesses, 0);
  assert.equal(legacyLoaded.state.nanoPurgeSuccesses, 0);
  assert.equal(legacyLoaded.state.swarmSyncSuccesses, 0);
  assert.equal(legacyLoaded.state.orbitalBerthSuccesses, 0);
  assert.equal(legacyLoaded.state.matterCompileSuccesses, 0);
  assert.equal(legacyLoaded.state.planetStripSuccesses, 0);
  assert.equal(legacyLoaded.state.stellarSyncSuccesses, 0);
  assert.equal(legacyLoaded.state.fleetSpreadSuccesses, 0);
  assert.equal(legacyLoaded.state.causalCollapseSuccesses, 0);
  assert.equal(legacyLoaded.state.surveysRecovered, 0);
  assert.equal(legacyLoaded.state.maxClickCombo, 0);
  assert.equal(legacyLoaded.state.capacitorStored, 0);
  assert.equal(legacyLoaded.state.capacitorClaims, 0);
  assert.equal(legacyLoaded.state.overclockMachine, null);
  assert.equal(legacyLoaded.state.overclockExpiresAt, 0);
  assert.equal(legacyLoaded.state.overclockCount, 0);
  assert.equal(legacyLoaded.state.foldExpiresAt, 0);
  assert.equal(legacyLoaded.state.foldCount, 0);
  assert.equal(legacyLoaded.state.gaugeTarget, 0);
  assert.equal(legacyLoaded.state.gaugeReadyAt, 0);
  assert.equal(legacyLoaded.state.gaugeHits, 0);
  assert.equal(legacyLoaded.state.catalystActive, false);
  assert.equal(legacyLoaded.state.catalystSeconds, 0);
  assert.equal(legacyLoaded.state.dispatchStored, 0);
  assert.equal(legacyLoaded.state.dispatchReturnsAt, 0);
  assert.equal(legacyLoaded.state.dispatchClaims, 0);
  assert.equal(legacyLoaded.state.patchCount, 0);
  assert.equal(legacyLoaded.state.windReadyAt, 0);
  assert.equal(legacyLoaded.state.windCount, 0);
  assert.equal(legacyLoaded.state.pulseReadyAt, 0);
  assert.equal(legacyLoaded.state.pulseCount, 0);
  assert.equal(legacyLoaded.state.scrapStored, 0);
  assert.equal(legacyLoaded.state.scrapClaims, 0);

  const interior = await server.ssrLoadModule('/src/game/interior.ts');
  const interiorState = createInitialState(0);
  assert.equal(interior.canOpenInterior(interiorState, 'autoClipper'), false);
  interiorState.machines.autoClipper = 1;
  assert.equal(interior.canOpenInterior(interiorState, 'autoClipper'), true);
  assert.equal(interior.interiorHarvestAmount(interiorState), 20);
  interiorState.machines.autoClipper = 100;
  const expectedHarvest = Math.max(20, clips.clickProduction(interiorState) * 5, clips.productionPerSecond(interiorState) * 2);
  assert.equal(interior.interiorHarvestAmount(interiorState), expectedHarvest);
  assert.ok(expectedHarvest > 20);
  const harvested = interior.applyInteriorHarvest(interiorState);
  assert.equal(harvested, expectedHarvest);
  assert.equal(interiorState.clips, expectedHarvest);
  assert.equal(interiorState.totalClips, expectedHarvest);
  assert.equal(interiorState.interiorHarvests, 1);
  const point = interior.randomInteriorPosition(() => 0);
  assert.equal(interior.randomWireTarget(() => 0), 8);
  assert.equal(interior.randomWireTarget(() => 1), 68);
  assert.equal(interior.wireTensionPosition(0), 0);
  assert.equal(interior.wireTensionPosition(500), 50);
  assert.equal(interior.wireTensionPosition(1_000), 100);
  assert.equal(interior.wireTensionPosition(1_500), 50);
  assert.equal(interior.isWireCalibrationSuccess(32, 20), true);
  assert.equal(interior.isWireCalibrationSuccess(45, 20), false);
  const wireState = createInitialState(0);
  wireState.machines.wireMachine = 1;
  const wireReward = interior.applyWireCalibrationReward(wireState, 3);
  assert.equal(wireReward, 300);
  assert.equal(wireState.wireCalibrationSuccesses, 3);
  const factoryBatch = interior.factoryInspectionBatch(() => 0.5);
  assert.equal(factoryBatch.length, 8);
  assert.equal(factoryBatch.filter((item) => item === 'standard').length, 4);
  assert.equal(factoryBatch.filter((item) => item === 'deformed').length, 4);
  const factoryState = createInitialState(0);
  factoryState.machines.clipFactory = 1;
  const factoryReward = interior.applyFactoryQualityReward(factoryState, 6);
  assert.equal(factoryReward, 3_000);
  assert.equal(factoryState.factoryQualityCorrect, 6);
  const traceShort = interior.randomTraceSequence(3, () => 0);
  assert.deepEqual(traceShort, [0, 1, 0]);
  const traceLong = interior.randomTraceSequence(4, () => 0.999);
  assert.deepEqual(traceLong, [3, 2, 3, 2]);
  assert.equal(traceShort.every((node, index) => index === 0 || node !== traceShort[index - 1]), true);
  assert.equal(interior.isTraceStepCorrect(traceShort, 0, 0), true);
  assert.equal(interior.isTraceStepCorrect(traceShort, 1, 0), false);
  const traceState = createInitialState(0);
  const traceReward = interior.applyTraceReward(traceState, 3);
  assert.equal(traceReward, 2_400);
  assert.equal(traceState.traceAiSuccesses, 3);
  assert.equal(traceState.clips, 2_400);
  assert.equal(traceState.totalClips, 2_400);
  const nanoWaste = interior.randomNanoWaste(() => 0);
  assert.equal(nanoWaste.length, 5);
  assert.equal(new Set(nanoWaste).size, 5);
  assert.equal(nanoWaste.every((cell) => cell >= 0 && cell < 16), true);
  assert.equal(interior.isNanoWasteCell(nanoWaste, nanoWaste[0]), true);
  const nanoClean = [...Array(16).keys()].find((cell) => !nanoWaste.includes(cell));
  assert.equal(interior.isNanoWasteCell(nanoWaste, nanoClean), false);
  const nanoState = createInitialState(0);
  const nanoReward = interior.applyNanoPurgeReward(nanoState, 3);
  assert.equal(nanoReward, 3_600);
  assert.equal(nanoState.nanoPurgeSuccesses, 3);
  assert.equal(nanoState.clips, 3_600);
  assert.equal(interior.swarmTarget(1), 3);
  assert.equal(interior.swarmTarget(2), 4);
  assert.equal(interior.swarmTarget(3), 5);
  assert.equal(interior.swarmTarget(4), 3);
  assert.equal(interior.isSwarmSyncSuccess(4, 4), true);
  assert.equal(interior.isSwarmSyncSuccess(3, 4), false);
  const swarmState = createInitialState(0);
  const swarmReward = interior.applySwarmSyncReward(swarmState, 3);
  assert.equal(swarmReward, 4_500);
  assert.equal(swarmState.swarmSyncSuccesses, 3);
  assert.equal(swarmState.clips, 4_500);
  assert.equal(interior.orbitalTarget(1), 3);
  assert.equal(interior.orbitalTarget(2), 4);
  assert.equal(interior.orbitalTarget(3), 3);
  assert.equal(interior.orbitalTarget(4), 4);
  assert.deepEqual(interior.randomOrbitalBlocked(3, () => 0), [0, 1]);
  assert.equal(interior.longestAvailableRun([0, 1]), 6);
  assert.equal(interior.isContiguousArc([true, true, true, false, false, false, false, false]), true);
  assert.equal(interior.isContiguousArc([true, false, false, false, false, false, false, true]), true);
  assert.equal(interior.isContiguousArc([true, false, true, false, false, false, false, false]), false);
  assert.equal(interior.isOrbitalBerthSuccess([true, true, true, false, false, false, false, false], [4, 5], 3), true);
  assert.equal(interior.isOrbitalBerthSuccess([true, true, false, true, false, false, false, false], [4, 5], 3), false);
  assert.equal(interior.isOrbitalBerthSuccess([true, true, true, false, false, false, false, false], [2, 5], 3), false);
  const orbitalState = createInitialState(0);
  const orbitalReward = interior.applyOrbitalBerthReward(orbitalState, 3);
  assert.equal(orbitalReward, 6_000);
  assert.equal(orbitalState.orbitalBerthSuccesses, 3);
  assert.equal(orbitalState.clips, 6_000);
  assert.deepEqual(interior.randomMatterBoard(() => 0), ['ore', 'dust', 'dust', 'flux', 'flux', 'ore']);
  assert.equal(interior.isMatterPair(['ore', 'dust', 'dust', 'flux', 'flux', 'ore'], 1, 2), true);
  assert.equal(interior.isMatterPair(['ore', 'dust', 'dust', 'flux', 'flux', 'ore'], 0, 1), false);
  assert.equal(interior.isMatterRoundSuccess([true, true, true, true, true, true]), true);
  assert.equal(interior.isMatterRoundSuccess([true, true, true, true, true, false]), false);
  assert.equal(interior.matterPairsRemaining([true, true, false, false, false, false]), 2);
  const matterState = createInitialState(0);
  const matterReward = interior.applyMatterCompileReward(matterState, 3);
  assert.equal(matterReward, 7_500);
  assert.equal(matterState.matterCompileSuccesses, 3);
  assert.equal(matterState.clips, 7_500);
  assert.equal(interior.planetOrderLength(1), 3);
  assert.equal(interior.planetOrderLength(4), 5);
  const planetOrder = interior.randomPlanetOrder(4, () => 0);
  assert.deepEqual(planetOrder, [0, 1, 0, 1]);
  assert.equal(planetOrder.every((quad, index) => index === 0 || quad !== planetOrder[index - 1]), true);
  assert.equal(interior.isPlanetStepCorrect(planetOrder, 0, 0), true);
  assert.equal(interior.isPlanetStepCorrect(planetOrder, 1, 0), false);
  const planetState = createInitialState(0);
  const planetReward = interior.applyPlanetStripReward(planetState, 3);
  assert.equal(planetReward, 9_000);
  assert.equal(planetState.planetStripSuccesses, 3);
  assert.equal(planetState.clips, 9_000);
  const stellarMask = interior.randomStellarMask(() => 0);
  assert.deepEqual(stellarMask, [false, true, true, false, false, false]);
  assert.equal(stellarMask.filter(Boolean).length, 2);
  assert.equal(interior.isStellarSyncSuccess(stellarMask, stellarMask), true);
  assert.equal(interior.isStellarSyncSuccess([true, true, true, false, false, false], stellarMask), false);
  const stellarState = createInitialState(0);
  const stellarReward = interior.applyStellarSyncReward(stellarState, 3);
  assert.equal(stellarReward, 10_500);
  assert.equal(stellarState.stellarSyncSuccesses, 3);
  assert.equal(stellarState.clips, 10_500);
  assert.equal(interior.randomFleetSeed(() => 0), 0);
  assert.deepEqual(interior.fleetNeighbors(0), [3, 1]);
  assert.deepEqual(interior.fleetNeighbors(4), [1, 7, 3, 5]);
  const fleetOwned = Array.from({ length: 9 }, () => false);
  fleetOwned[0] = true;
  assert.equal(interior.canClaimFleetCell(fleetOwned, 1), true);
  assert.equal(interior.canClaimFleetCell(fleetOwned, 2), false);
  assert.equal(interior.canClaimFleetCell(fleetOwned, 0), false);
  assert.equal(interior.isFleetSpreadSuccess(Array.from({ length: 9 }, () => true)), true);
  const fleetState = createInitialState(0);
  const fleetReward = interior.applyFleetSpreadReward(fleetState, 3);
  assert.equal(fleetReward, 12_000);
  assert.equal(fleetState.fleetSpreadSuccesses, 3);
  assert.equal(fleetState.clips, 12_000);
  assert.deepEqual(interior.randomCausalGauges(() => 0), [0, 1, 2, 3]);
  assert.equal(interior.isCausalConverged([2, 2, 2, 2]), true);
  assert.equal(interior.isCausalConverged([0, 1, 2, 3]), false);
  assert.deepEqual(interior.incrementCausalGauge([0, 1, 2, 3], 0), [1, 1, 2, 3]);
  assert.deepEqual(interior.incrementCausalGauge([0, 1, 2, 3], 3), [0, 1, 2, 0]);
  assert.equal(interior.causalSpan([0, 1, 2, 3]), 3);
  const causalState = createInitialState(0);
  const causalReward = interior.applyCausalCollapseReward(causalState, 3);
  assert.equal(causalReward, 13_500);
  assert.equal(causalState.causalCollapseSuccesses, 3);
  assert.equal(causalState.clips, 13_500);
  assert.equal(point.x, 12);
  assert.equal(point.y, 18);

  console.log('Game logic checks passed.');
} finally {
  await server.close();
}
